import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";

import { inter, notoSerif, sourceCode } from "@/fonts/fonts";
import { FontProvider } from "@/contexts/font-context";
import Navbar from "./components/navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${notoSerif.variable} ${sourceCode.variable} antialiased`}
      >
        <ThemeProvider attribute="class" enableSystem>
          <FontProvider>
            <Navbar />
            {children}
          </FontProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
